import React from 'react';

const projects = [
    {name:'Pizzaria Di Belle',content:'Percebi que eu tinha varios outros projetos, mas nenhum com o estilo de uma landing page estatica, então veio a ideia de criar a Pizzaria di Belle, como era um projeto simples decidi utilizar HTML5, CSS3 e JavaScript.',linkGit:'https://github.com/vinimachad/pizzaria-di-belle'},
    {name:'Instagram Clone',content:'Eu recriei o Instagram com a visão de aprender a fundo as funções do JavaScript, porque até o momento eu estava estudando apenas designs, layouts e etc, então decidi sair da minha zona de conforto e tentar algo mais complexo, senti que quando "finalizei" o projeto havia completado meu objetivo.',linkGit:'https://github.com/vinimachad/clone-instagram'},
    {name:'WhatsApp Clone',content:'Quando iniciei o projeto, estava tranquilo pois acreditava que seria parecido com o sistema do Instagram, e sim algumas funcionabilidades se pareciam mas nao completamente, posso dizer que depois da criação do instagram e deste projeto, eu obtive uma melhora muito grande em questão de pesquisas e lógica de programação.',linkGit:'https://github.com/vinimachad/WhatsApp-clone'},
    {name:'GetKcal',content:'Quando iniciei o projeto, estava tranquilo pois acreditava que seria parecido com o sistema do Instagram, e sim algumas funcionabilidades se pareciam mas nao completamente, posso dizer que depois da criação do instagram e deste projeto, eu obtive uma melhora muito grande em questão de pesquisas e lógica de programação.',linkGit:'https://github.com/vinimachad/WhatsApp-clone'},
    {name:'Dark Mode',content:'Quando iniciei o projeto, estava tranquilo pois acreditava que seria parecido com o sistema do Instagram, e sim algumas funcionabilidades se pareciam mas nao completamente, posso dizer que depois da criação do instagram e deste projeto, eu obtive uma melhora muito grande em questão de pesquisas e lógica de programação.',linkGit:'https://github.com/vinimachad/WhatsApp-clone'},
    {name:'Kiwi Imobiliaria',content:'Quando iniciei o projeto, estava tranquilo pois acreditava que seria parecido com o sistema do Instagram, e sim algumas funcionabilidades se pareciam mas nao completamente, posso dizer que depois da criação do instagram e deste projeto, eu obtive uma melhora muito grande em questão de pesquisas e lógica de programação.',linkGit:'https://github.com/vinimachad/WhatsApp-clone'},
    {name:'Dash Board Of Notation',content:'Quando iniciei o projeto, estava tranquilo pois acreditava que seria parecido com o sistema do Instagram, e sim algumas funcionabilidades se pareciam mas nao completamente, posso dizer que depois da criação do instagram e deste projeto, eu obtive uma melhora muito grande em questão de pesquisas e lógica de programação.',linkGit:'https://github.com/vinimachad/WhatsApp-clone'},
    {name:'Border Generator',content:'Quando iniciei o projeto, estava tranquilo pois acreditava que seria parecido com o sistema do Instagram, e sim algumas funcionabilidades se pareciam mas nao completamente, posso dizer que depois da criação do instagram e deste projeto, eu obtive uma melhora muito grande em questão de pesquisas e lógica de programação.',linkGit:'https://github.com/vinimachad/WhatsApp-clone'},
    {name:'Clock',content:'Quando iniciei o projeto, estava tranquilo pois acreditava que seria parecido com o sistema do Instagram, e sim algumas funcionabilidades se pareciam mas nao completamente, posso dizer que depois da criação do instagram e deste projeto, eu obtive uma melhora muito grande em questão de pesquisas e lógica de programação.',linkGit:'https://github.com/vinimachad/WhatsApp-clone'},
]

export default projects;