import React from 'react';

const projects = [
    {name:'Pizzaria Di Belle',content:'Percebi que eu tinha varios outros projetos, mas nenhum com o estilo de uma landing page estatica, então veio a ideia de criar a Pizzaria di Belle, como era um projeto simples decidi utilizar HTML5, CSS3 e JavaScript.',linkGit:'https://github.com/vinimachad/pizzaria-di-belle'},
    {name:'Instagram Clone',content:'Eu recriei o Instagram com a visão de aprender a fundo as funções do JavaScript, porque até o momento eu estava estudando apenas designs, layouts e etc, então decidi sair da minha zona de conforto e tentar algo mais complexo, senti que quando "finalizei" o projeto havia completado meu objetivo.',linkGit:'https://github.com/vinimachad/clone-instagram'},
    {name:'WhatsApp Clone',content:'Quando iniciei o projeto, estava tranquilo pois acreditava que seria parecido com o sistema do Instagram, e sim algumas funcionabilidades se pareciam mas nao completamente, posso dizer que depois da criação do instagram e deste projeto, eu obtive uma melhora muito grande em questão de pesquisas e lógica de programação.',linkGit:'https://github.com/vinimachad/WhatsApp-clone'},
    {name:'GetKcal',content:'Como eu sigo alguns perfis no instagram sobre JS, React e etc, acompanhando o stories do @imateus.silva, vi que ele estava constuindo uma aplicação interessante e decidi assistir o video no canal dele, acabei construindo a aplicação dele.',linkGit:'https://github.com/vinimachad/getKcal'},
    {name:'Dark Mode',content:'Quando iniciei o projeto, estava tranquilo pois acreditava que seria parecido com o sistema do Instagram, e sim algumas funcionabilidades se pareciam mas nao completamente, posso dizer que depois da criação do instagram e deste projeto, eu obtive uma melhora muito grande em questão de pesquisas e lógica de programação.',linkGit:'https://github.com/vinimachad/WhatsApp-clone'},
    {name:'Kiwi Imobiliaria',content:'O kiwi Imobiliaria foi um projetinho para ajudar alguns amigos meus a entender algumas funções do JS, CSS3 e HTML5',linkGit:'https://github.com/vinimachad/imobiliaria'},
    {name:'Dash Board Of Notation',content:'A ideia do projeto é parecida com um Todo-List, mas com um olhar além, com alarme de atividade expirade, concluida e etc. Acabei nao "finalizando" o projeto pois na época estava bem leigo no back-end. ',linkGit:'https://github.com/vinimachad/dashboard-of-notation'},
    {name:'Border Generator',content:'Border Generator foi o meu primeiro projetinho, com o intuido de quebra galho para algumas tarefas no CSS3, pretendo criar mais alguns geradores.',linkGit:'https://github.com/vinimachad/border-genetator'},
    {name:'Clock',content:'O unico intuito do projeto mesmo era aprender mais algumas ideias de design utilizando o box-shadow do CSS3, utilizando inset, por vez aprendi outras pequenas funcionalidades do JS.',linkGit:'https://github.com/vinimachad/clock'},
]

export default projects;